# tests/conftest.py
#
# Golden fixture harness for the saprfclib RE spike.
# Provides: load_fixture(), compare_bytes(), discover_fixtures(), Fixture, GOLDEN_ROOT.

import json
from dataclasses import dataclass
from pathlib import Path

GOLDEN_ROOT = Path(__file__).parent / "golden"


@dataclass
class Fixture:
    message_type: str
    field_annotations: list[dict]
    expected_parse: dict
    capture_source: str
    binja_ref: str
    raw_bytes: bytes  # full NI-framed bytes
    payload_bytes: bytes  # stripped payload (NI/CPIC header removed)


def load_fixture(fixture_dir: Path, name: str) -> Fixture:
    """Load a JSON+.bin fixture pair by name (without extension).

    Args:
        fixture_dir: one of tests/golden/{framing,serialization,handshake,synthetic}/
        name: fixture name without extension (e.g., 'stfc_connection_request')

    Returns:
        Fixture with both raw_bytes and parsed metadata

    Raises:
        FileNotFoundError: if .json or .bin is missing
        ValueError: if JSON schema is invalid
    """
    json_path = fixture_dir / f"{name}.json"
    bin_path = fixture_dir / f"{name}.bin"

    meta = json.loads(json_path.read_text())
    raw = bin_path.read_bytes()

    # Validate required JSON schema keys (D-07)
    required_keys = {
        "message_type",
        "field_annotations",
        "expected_parse",
        "capture_source",
        "binja_ref",
    }
    missing = required_keys - meta.keys()
    if missing:
        raise ValueError(f"Fixture JSON {json_path} missing required keys: {missing}")

    # NI header = 4 bytes (confirmed by BN decompilation of NiIWrite/NiIRead)
    NI_HEADER_LEN = meta.get("ni_header_length", 4)
    payload = raw[NI_HEADER_LEN:]

    return Fixture(
        message_type=meta["message_type"],
        field_annotations=meta["field_annotations"],
        expected_parse=meta["expected_parse"],
        capture_source=meta["capture_source"],
        binja_ref=meta["binja_ref"],
        raw_bytes=raw,
        payload_bytes=payload,
    )


def compare_bytes(
    actual: bytes | bytearray | memoryview,
    expected: bytes,
    annotations: list[dict],
) -> list[str]:
    """Compare actual bytes against expected, skipping variable fields.

    Args:
        actual:      bytes received / generated by the codec
        expected:    bytes from the .bin fixture
        annotations: field_annotations list from the fixture JSON

    Returns:
        List of mismatch descriptions (empty = pass).
        Variable-annotated fields are skipped entirely.
    """
    if len(actual) != len(expected):
        return [f"length mismatch: actual={len(actual)} expected={len(expected)}"]

    # Build a bitmask of bytes to skip (variable fields)
    skip: set[int] = set()
    for ann in annotations:
        if ann.get("type") == "variable":
            for i in range(ann["offset"], ann["offset"] + ann["length"]):
                skip.add(i)

    mismatches = []
    for i, (a, e) in enumerate(zip(bytes(actual), expected, strict=False)):
        if i in skip:
            continue
        if a != e:
            mismatches.append(f"offset 0x{i:04x}: actual=0x{a:02x} expected=0x{e:02x}")
    return mismatches


def discover_fixtures(gate_dir: Path) -> list[tuple[Path, str]]:
    """Discover all fixtures in a gate directory for parametrized tests.

    Returns list of (fixture_dir, name) pairs for pytest.mark.parametrize.
    Returns empty list when no pairs found (not an error).
    """
    results = []
    for json_path in gate_dir.glob("*.json"):
        bin_path = json_path.with_suffix(".bin")
        if bin_path.exists():
            results.append((gate_dir, json_path.stem))
    return results
