name: Feature request
description: Propose new functionality
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed API or behaviour
      render: python

  - type: checkboxes
    id: constraints
    attributes:
      label: Constraints
      options:
        - label: This can be implemented in pure Python with no new native dependency
          required: true
